# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: fc40d5a286f34ea569395a9d6f33c881dbc81a6494704c412d7a290a7cdd37e79198d6147c35c697012c0a1331a994ea50a00fc72c75ecf7b560d0d81523faaa

test:
  secret_key_base: 3484e034664828d17794bffee0b500e2d8cd3fcc7346d590bafd0103ec30cbf55b29d36862433c3c9a790c1f57bd2fbe74403c6e3302c30950d6be0031c21df1

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
